# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhOps < Formula
  desc "One-click GitHub operations via OAuth for AI agents"
  homepage "https://github.com/SammyLin/gh-ops"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.1.3/gh-ops_1.1.3_darwin_amd64.tar.gz"
      sha256 "3f937938ee3032fb3a1320ddc2eb92de9aacab5e7a1ca4c6af44b28f9d41984c"

      define_method(:install) do
        bin.install "gh-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.1.3/gh-ops_1.1.3_darwin_arm64.tar.gz"
      sha256 "640202efc40f8fa041ec55b0374a9f7a25594d70e36258f0307d1308d939e673"

      define_method(:install) do
        bin.install "gh-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.1.3/gh-ops_1.1.3_linux_amd64.tar.gz"
      sha256 "e8a89aa3d6b4422737f853bf32e28fb36cb9c19dc5b6a3314aef2b7f08c2eacf"
      define_method(:install) do
        bin.install "gh-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.1.3/gh-ops_1.1.3_linux_arm64.tar.gz"
      sha256 "4567f6bbbed6f57d72c87a976004542f8857b1307c70af223e3b86f330aec03d"
      define_method(:install) do
        bin.install "gh-ops"
      end
    end
  end

  test do
    assert_match "One-click GitHub operations", shell_output("#{bin}/gh-ops --help")
  end
end
