# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-ops" do
  name "gh-ops"
  desc "One-click GitHub operations via OAuth for AI agents"
  homepage "https://github.com/SammyLin/gh-ops"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-ops"

  on_macos do
    on_intel do
      url "https://github.com/SammyLin/gh-ops/releases/download/v#{version}/gh-ops_#{version}_darwin_amd64.tar.gz"
      sha256 "045ce2b369de5a55d6df4218395ffb556f85b6fdb1644b46b2f601eae64dbbb2"
    end
    on_arm do
      url "https://github.com/SammyLin/gh-ops/releases/download/v#{version}/gh-ops_#{version}_darwin_arm64.tar.gz"
      sha256 "870d3f0f3622e72acc01c23369c370c13da7406312151a237a632f0ef7ff615f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SammyLin/gh-ops/releases/download/v#{version}/gh-ops_#{version}_linux_amd64.tar.gz"
      sha256 "4a2294c16c23f7dc8d6c74f86d6d0258a676211a24fbfd52e17f26f876bb2b5c"
    end
    on_arm do
      url "https://github.com/SammyLin/gh-ops/releases/download/v#{version}/gh-ops_#{version}_linux_arm64.tar.gz"
      sha256 "9bab9c95e10950d5cda126abd7d5a52b74d469265788617a20db2433442b71c3"
    end
  end

  # No zap stanza required
end
