# This file was generated by GoReleaser. DO NOT EDIT.
cask "psw-cli" do
  name "psw-cli"
  desc "Secure CLI password manager with age encryption and macOS Keychain"
  homepage "https://github.com/SammyLin/psw-cli"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "psw-cli"
  binary "psw-cli-verify"

  on_macos do
    on_intel do
      url "https://github.com/SammyLin/psw-cli/releases/download/v#{version}/psw-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "9b88e5d13ed59760a27f224d66c634afd8972a481309ec4a5324a5c87e5bd435"
    end
    on_arm do
      url "https://github.com/SammyLin/psw-cli/releases/download/v#{version}/psw-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "1df4d6c8839670746a189e828aa0e2b12258ea175b4dc103003590a16451bb81"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SammyLin/psw-cli/releases/download/v#{version}/psw-cli_#{version}_linux_amd64.tar.gz"
      sha256 "a00feef0c53dcae85bec226f2d59824f7b4cc72fd85583106302124dbb9f6bd0"
    end
    on_arm do
      url "https://github.com/SammyLin/psw-cli/releases/download/v#{version}/psw-cli_#{version}_linux_arm64.tar.gz"
      sha256 "1c4c02c56bfe130ef822ec127b1494294cc8430f02f537c828170396f9301a7e"
    end
  end

  # No zap stanza required
end
