# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhOps < Formula
  desc "One-click GitHub operations via OAuth for AI agents"
  homepage "https://github.com/SammyLin/gh-ops"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.2.0/gh-ops_1.2.0_darwin_amd64.tar.gz"
      sha256 "292f580501346ae87a360427a2f3b2eca12b9e12089afd374ed1ce6499b30947"

      define_method(:install) do
        bin.install "gh-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.2.0/gh-ops_1.2.0_darwin_arm64.tar.gz"
      sha256 "76df5c867f688ba1d27bb25e3d5bb2732de8f118185e293f4370866492584aa5"

      define_method(:install) do
        bin.install "gh-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.2.0/gh-ops_1.2.0_linux_amd64.tar.gz"
      sha256 "ff95ccc28d4d121cbb1a97ee10dcf9b85ef3835f3175938ddd04cc5c3bb55b9f"
      define_method(:install) do
        bin.install "gh-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SammyLin/gh-ops/releases/download/v1.2.0/gh-ops_1.2.0_linux_arm64.tar.gz"
      sha256 "8a6d66d627ea6db5f6d2136d866740de776aa742706d9f6edf9131f4de0804e1"
      define_method(:install) do
        bin.install "gh-ops"
      end
    end
  end

  test do
    assert_match "One-click GitHub operations", shell_output("#{bin}/gh-ops --help")
  end
end
